// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.NestJS.Authentication.Templates.Auth.AuthModule
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.TypeScript.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Authentication\Templates\Auth\AuthModule\AuthModuleTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class AuthModuleTemplate : TypeScriptTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import { Module } from \'@nestjs/common\';\r\nimport { ConfigModule, ConfigService } " +
                    "from \'@nestjs/config\';\r\nimport { JwtModule } from \'@nestjs/jwt\';\r\nimport { Passp" +
                    "ortModule } from \'@nestjs/passport\';\r\n\r\n@Module({\r\n  imports: [\r\n    ");
            
            #line 17 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Authentication\Templates\Auth\AuthModule\AuthModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetUsersModuleName()));
            
            #line default
            #line hidden
            this.Write(",\r\n    PassportModule,\r\n    JwtModule.registerAsync({\r\n      imports: [ConfigModu" +
                    "le],\r\n      useFactory: (config: ConfigService) => ({\r\n        secret: config.ge" +
                    "t(\'");
            
            #line 22 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Authentication\Templates\Auth\AuthModule\AuthModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EnvironmentVariables.JwtKey));
            
            #line default
            #line hidden
            this.Write("\'),\r\n        signOptions: { expiresIn: \'1h\' },\r\n      }),\r\n      inject: [ConfigS" +
                    "ervice],\r\n    }),\r\n  ],\r\n  controllers: [\r\n    ");
            
            #line 29 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Authentication\Templates\Auth\AuthModule\AuthModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetAuthControllerName()));
            
            #line default
            #line hidden
            this.Write("\r\n  ],\r\n  providers: [");
            
            #line 31 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Authentication\Templates\Auth\AuthModule\AuthModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetProviders()));
            
            #line default
            #line hidden
            this.Write("],\r\n  exports: [");
            
            #line 32 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Authentication\Templates\Auth\AuthModule\AuthModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetAuthServiceName()));
            
            #line default
            #line hidden
            this.Write("],\r\n})\r\nexport class ");
            
            #line 34 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Authentication\Templates\Auth\AuthModule\AuthModuleTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" {}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
