// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.NestJS.Authorization.Templates.RolesDecorator
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.TypeScript.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Authorization\Templates\RolesDecorator\RolesDecoratorTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RolesDecoratorTemplate : TypeScriptTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import { SetMetadata } from \'@nestjs/common\';\r\n\r\nexport const ROLES_KEY = \'roles\'" +
                    ";\r\nexport const ");
            
            #line 13 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Authorization\Templates\RolesDecorator\RolesDecoratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" = (...roles: ");
            
            #line 13 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Authorization\Templates\RolesDecorator\RolesDecoratorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetRoleEnumName()));
            
            #line default
            #line hidden
            this.Write("[]) => SetMetadata(ROLES_KEY, roles);");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
