// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.NestJS.Controllers.Templates.Service
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.TypeScript.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Services.Api;
    using Intent.Modules.TypeScript.Weaving.Decorators;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Service\ServiceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ServiceTemplate : TypeScriptTemplateBase<Intent.Modelers.Services.Api.ServiceModel, Intent.Modules.NestJS.Controllers.Templates.Service.ServiceDecorator>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import { Injectable } from \'@nestjs/common\';\r\n\r\n@Injectable()\r\nexport class ");
            
            #line 15 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Service\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" {\r\n\r\n  //@IntentCanAdd()\r\n  constructor(");
            
            #line 18 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Service\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetConstructorParameters()));
            
            #line default
            #line hidden
            this.Write(") {}\r\n");
            
            #line 19 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Service\ServiceTemplate.tt"
  foreach(var operation in Model.Operations) { 
            
            #line default
            #line hidden
            this.Write("\r\n  ");
            
            #line 21 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Service\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.IntentIgnoreBodyDecorator()));
            
            #line default
            #line hidden
            this.Write("\r\n  async ");
            
            #line 22 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Service\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 22 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Service\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetParameterDefinitions(operation)));
            
            #line default
            #line hidden
            this.Write("): Promise<");
            
            #line 22 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Service\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetReturnType(operation)));
            
            #line default
            #line hidden
            this.Write("> {\r\n    ");
            
            #line 23 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Service\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetImplementation(operation)));
            
            #line default
            #line hidden
            this.Write("\r\n  }\r\n");
            
            #line 25 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Service\ServiceTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
