// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.Npm.Templates.PackageJsonFile
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Metadata.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.Npm\Templates\PackageJsonFile\PackageJsonFileTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class PackageJsonFileTemplate : IntentTemplateBase<object, Intent.Modules.Npm.Templates.PackageJsonFile.PackageJsonFileDecorator>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("{\r\n  \"name\": \"nestjs-petclinic-rest\",\r\n  \"private\": true,\r\n  \"version\": \"1.0.0\",\r" +
                    "\n  \"description\": \"NestJS Pet Clinic rest services\",\r\n  \"license\": \"MIT\",\r\n  \"sc" +
                    "ripts\": {\r\n  },\r\n  \"dependencies\": {\r\n  },\r\n  \"devDependencies\": {\r\n  },\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
