//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.10
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intent.Modules.NestJS.Authentication.Templates.Users.UserContext {
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.TypeScript.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using System;
    
    
    public partial class UserContextTemplate : TypeScriptTemplateBase<object, Intent.Modules.NestJS.Authentication.Templates.Users.UserContext.UserContextDecorator> {
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 10 ""
            this.Write("export class ");
            
            #line default
            #line hidden
            
            #line 10 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( ClassName ));
            
            #line default
            #line hidden
            
            #line 10 ""
            this.Write(" {\r\n  userId: number;\r\n  username: string;\r\n  password?: string;\r\n");
            
            #line default
            #line hidden
            
            #line 14 ""
 foreach (var member in GetDecoratorMembers()) { 
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write("  ");
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( member ));
            
            #line default
            #line hidden
            
            #line 15 ""
            this.Write(";\r\n");
            
            #line default
            #line hidden
            
            #line 16 ""
 } 
            
            #line default
            #line hidden
            
            #line 17 ""
            this.Write("}");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
