// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.NestJS.Authorization.Templates.RolesGuard
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.TypeScript.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modules.NestJS.Authentication.Templates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Authorization\Templates\RolesGuard\RolesGuardTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RolesGuardTemplate : TypeScriptTemplateBase<object>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import { Injectable, ExecutionContext } from \'@nestjs/common\';\r\nimport { Reflecto" +
                    "r } from \'@nestjs/core\';\r\nimport { ROLES_KEY } from \'../roles.decorator\';\r\n\r\n@In" +
                    "jectable()\r\nexport class ");
            
            #line 16 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Authorization\Templates\RolesGuard\RolesGuardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" extends ");
            
            #line 16 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Authorization\Templates\RolesGuard\RolesGuardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetJwtAuthGuardName()));
            
            #line default
            #line hidden
            this.Write(" {\r\n  constructor(reflector: Reflector) {\r\n    super(reflector);\r\n  }\r\n\r\n  async " +
                    "canActivate(context: ExecutionContext): Promise<boolean> {\r\n    const requiredRo" +
                    "les = this.reflector.getAllAndOverride<");
            
            #line 22 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Authorization\Templates\RolesGuard\RolesGuardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetRoleEnumName()));
            
            #line default
            #line hidden
            this.Write(@"[]>(ROLES_KEY, [
      context.getHandler(),
      context.getClass(),
    ]);

    if (!requiredRoles || this.isPublic(context)) {
      return true;
    }

    if (!(await super.canActivate(context))) {
      return false;
    }

    const { user } = context.switchToHttp().getRequest();
    return requiredRoles.some((role) => user.roles?.includes(role));
  }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
