// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.NestJS.Controllers.Templates.DtoModel
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.TypeScript.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Services.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class DtoModelTemplate : TypeScriptTemplateBase<Intent.Modelers.Services.Api.DTOModel, Intent.Modules.NestJS.Controllers.Templates.DtoModel.DtoModelDecorator>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nexport");
            
            #line 12 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetAbstractDefinition()));
            
            #line default
            #line hidden
            this.Write(" class ");
            
            #line 12 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            
            #line 12 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetGenericTypeParameters(Model.GenericTypes)));
            
            #line default
            #line hidden
            
            #line 12 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetBaseType()));
            
            #line default
            #line hidden
            this.Write(" {");
            
            #line 12 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
 foreach(var field in Model.Fields) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 14 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
 foreach (var decorator in GetFieldDecorators(field)) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 15 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decorator));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 16 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 17 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 17 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.TypeReference.IsNullable ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 17 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(field.TypeReference)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 18 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
  }
    if (Model.IsMapped && !Model.IsAbstract) {
            
            #line default
            #line hidden
            this.Write("\r\n  static from");
            
            #line 21 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(Model.Mapping)));
            
            #line default
            #line hidden
            
            #line 21 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetGenericTypeParameters(Model.GenericTypes.Concat(MappedModel.GenericTypes))));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 21 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MappedModel.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 21 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(Model.Mapping)));
            
            #line default
            #line hidden
            
            #line 21 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetGenericTypeParameters(MappedModel.GenericTypes)));
            
            #line default
            #line hidden
            this.Write("): ");
            
            #line 21 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            
            #line 21 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetGenericTypeParameters(Model.GenericTypes)));
            
            #line default
            #line hidden
            this.Write(" {\r\n    if (");
            
            #line 22 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Mapping.Element.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(" == null) {\r\n      return null;\r\n    }\r\n    const dto = new ");
            
            #line 25 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            
            #line 25 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetGenericTypeParameters(Model.GenericTypes)));
            
            #line default
            #line hidden
            this.Write("();\r\n    ");
            
            #line 26 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMappings()));
            
            #line default
            #line hidden
            this.Write("\r\n    return dto;\r\n  }\r\n\r\n  static requiredRelations: string[] = [");
            
            #line 30 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", GetRequiredRelations().Select(x => "\"" + x + "\""))));
            
            #line default
            #line hidden
            this.Write("];\r\n");
            
            #line 31 "C:\Dev\Intent.Modules.NodeJS\Modules\Intent.Modules.NestJS.Controllers\Templates\DtoModel\DtoModelTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
