// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.NestJS.Controllers.Templates.Controller
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.TypeScript.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Services.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ControllerTemplate : TypeScriptTemplateBase<Intent.Modelers.Services.Api.ServiceModel, Intent.Modules.NestJS.Controllers.Templates.Controller.ControllerDecorator>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import { Controller, Logger } from \'@nestjs/common\';\r\n\r\n");
            
            #line 13 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
 foreach (var decorator in GetClassDecorators()) { 
            
            #line default
            #line hidden
            
            #line 14 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decorator));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 15 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("export class ");
            
            #line 16 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" {\r\n  logger = new Logger(\'");
            
            #line 17 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("\');\r\n\r\n  constructor(private readonly ");
            
            #line 19 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ServiceClassName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 19 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ServiceClassName));
            
            #line default
            #line hidden
            this.Write(") {}\r\n");
            
            #line 20 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
 foreach(var operation in Model.Operations) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 22 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
 foreach (var decorator in GetOperationDecorators(operation)) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 23 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(decorator));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 24 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("  async ");
            
            #line 25 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 25 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetOperationParameters(operation)));
            
            #line default
            #line hidden
            this.Write("): Promise<");
            
            #line 25 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetReturnType(operation)));
            
            #line default
            #line hidden
            this.Write("> {\r\n");
            
            #line 26 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
      if (operation.ReturnType != null) { 
            
            #line default
            #line hidden
            this.Write("    var result = await this.");
            
            #line 27 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ServiceClassName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 27 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 27 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetParameters(operation)));
            
            #line default
            #line hidden
            this.Write(");\r\n    return result;\r\n");
            
            #line 29 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
      } else { 
            
            #line default
            #line hidden
            this.Write("    return await this.");
            
            #line 30 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ServiceClassName.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 30 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 30 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetParameters(operation)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 31 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
      } 
            
            #line default
            #line hidden
            this.Write("  }\r\n");
            
            #line 33 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.NestJS.Controllers\Templates\Controller\ControllerTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
