// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Module.TypeScript.Domain.Templates.Entity
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.TypeScript.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Domain.Api;
    using Intent.Modules.TypeScript.Weaving.Decorators;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EntityTemplate : TypeScriptTemplateBase<Intent.Modelers.Domain.Api.ClassModel, Intent.Module.TypeScript.Domain.Templates.Entity.EntityDecorator>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 12 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetClassDecorators()));
            
            #line default
            #line hidden
            this.Write("\r\nexport class ");
            
            #line 13 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            
            #line 13 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDerivedFrom()));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 14 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDecoratorsOutput(x => x.GetBeforeFields())));
            
            #line default
            #line hidden
            
            #line 14 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
  foreach(var attribute in Model.Attributes) { 
            
            #line default
            #line hidden
            
            #line 15 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((Model.Attributes.IndexOf(attribute) == 0 ? "" : @"
")));
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 16 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetAttributeDecorators(attribute)));
            
            #line default
            #line hidden
            
            #line 16 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 16 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.TypeReference.IsNullable ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 16 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(attribute.TypeReference)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 17 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
  } 
            
            #line default
            #line hidden
            
            #line 18 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
  foreach(var association in GetAssociationsRequiringFields()) { 
            
            #line default
            #line hidden
            this.Write("\r\n  ");
            
            #line 20 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetAssociationDecorators(association)));
            
            #line default
            #line hidden
            
            #line 20 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.Name.ToCamelCase()));
            
            #line default
            #line hidden
            
            #line 20 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(association.IsNullable ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 20 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(association)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 21 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
  } 
            
            #line default
            #line hidden
            
            #line 21 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDecoratorsOutput(x => x.GetAfterFields())));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 22 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
  foreach(var operation in Model.Operations) { 
            
            #line default
            #line hidden
            this.Write("\r\n  ");
            
            #line 24 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.IntentIgnoreBodyDecorator()));
            
            #line default
            #line hidden
            this.Write("\r\n  ");
            
            #line 25 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 25 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.GetMethodParameters(operation.Parameters)));
            
            #line default
            #line hidden
            this.Write("): ");
            
            #line 25 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ReturnType != null ? GetTypeName(operation.ReturnType) : "void"));
            
            #line default
            #line hidden
            this.Write(" {\r\n    throw new Error(\"Write your implementation for this operation here...\");\r" +
                    "\n  }\r\n");
            
            #line 28 "C:\Dev\Intent.Modules.NodeJS\Intent.Module.TypeScript.Domain\Templates\Entity\EntityTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
