// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Intent.Modules.TypeORM.Entities.Templates.EntityTemplate
{
    using System.Collections.Generic;
    using System.Linq;
    using Intent.Modules.Common;
    using Intent.Modules.Common.Templates;
    using Intent.Modules.Common.TypeScript.Templates;
    using Intent.Templates;
    using Intent.Metadata.Models;
    using Intent.Modelers.Domain.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EntityTemplate : TypeScriptTemplateBase<ClassModel>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("import { Entity, Column, ManyToMany, JoinTable } from \'typeorm\';\r\n\r\n@Entity(\'jhi_" +
                    "");
            
            #line 13 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName.ToLower()));
            
            #line default
            #line hidden
            this.Write("\')\r\nexport class ");
            
            #line 14 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" extends ");
            
            #line 14 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetBaseClassName()));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 15 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
  foreach(var attribute in Model.Attributes) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 16 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetAttributeDecorators(attribute)));
            
            #line default
            #line hidden
            this.Write("\r\n  ");
            
            #line 17 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            
            #line 17 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.TypeReference.IsNullable ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 17 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(attribute.TypeReference)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 19 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
  } 
            
            #line default
            #line hidden
            
            #line 20 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
  foreach(var associationEnd in Model.AssociatedClasses.Where(x => x.IsNavigable)) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 21 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetAssociationDecorators(associationEnd)));
            
            #line default
            #line hidden
            this.Write("\r\n  ");
            
            #line 22 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associationEnd.Name));
            
            #line default
            #line hidden
            
            #line 22 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(associationEnd.IsNullable ? "?" : ""));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 22 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetTypeName(associationEnd)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 24 "C:\Dev\Intent.Modules.NodeJS\Intent.Modules.TypeORM.Entities\Templates\EntityTemplate\EntityTemplate.tt"
  } 
            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
